version: '3'

services:

  transmission:
    container_name: transmission
    image: dperson/transmission
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Bucharest
      - TR_IDLE_SEEDING_LIMIT_ENABLED=true
      - TR_IDLE_SEEDING_LIMIT=600
      - TR_RATIO_LIMIT_ENABLED=true
      - TR_RATIO_LIMIT=4
      - TR_DOWNLOAD_DIR=/downloads
      - TR_INCOMPLETE_DIR_ENABLED=false
      - TR_RENAME_PARTIAL_FILES=true
      - TR_DHT_ENABLED=false
      - TR_PEX_ENABLED=false
      - USERID=0
      - GROUPID=1001
    volumes:
      - /opt/config/transmission:/var/lib/transmission-daemon/info
      #set transmission or sonarr download folder to /downloads
      - /mnt/atlas/downloads/complete:/downloads
      - /mnt/atlas/downloads/temp:/var/lib/transmission-daemon/incomplete

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    depends_on:
      - transmission
    network_mode: host
    environment:
      - TZ=Europe/Bucharest
      - PUID=0
      - PGID=1001
    volumes:
      - /opt/config/sonarr:/config
      - /mnt/atlas/tv:/tv
      - /mnt/atlas/downloads/complete:/downloads

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    depends_on:
      - transmission
    network_mode: host
    environment:
      - TZ=Europe/Bucharest
      - PUID=0
      - PGID=1001
    volumes:
      - /opt/config/radarr:/config
      - /mnt/atlas/movies:/movies
      - /mnt/atlas/downloads/complete:/downloads

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Bucharest
      - PUID=0
      - PGID=1001
    volumes:
      - /opt/config/jackett:/config
      - /mnt/atlas/downloads:/downloads
  
  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Bucharest
      - UMASK_SET=<022>
      - PUID=0
      - PGID=1001
    volumes:
      - /opt/config/deluge:/config
      - /mnt/atlas/movies:/movies
      - /mnt/atlas/tv:/tv
      - /mnt/atlas/downloads:/downloads
  